### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by thevahidal**
Add contributors section

### CODE REVIEW

**Review by IanMayo — APPROVED** [review]
I'll have to presume the clever MD is correct

**Comment by thevahidal** [comment]
@all-contributors please add @IanMayo for <contributions>

**Comment by thevahidal** [comment]
@all-contributors please add @thevahidal for code

**Comment by thevahidal** [comment]
@all-contributors
please add @IanMayo  for code. 
please add @AbegaM  for code.
please add @HanzCEO   for code. 
please add @KoenDG   for code.

**Pull request merged**
